[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
# framework
rocket = { version = "0.5.1", features = ["secrets", "json"] }
rocket_ws = { version = "0.1.1" }
tokio = { version = "1.45.1" }

# database
rusqlite = { version = "0.37.0", features = ["bundled", "chrono"] }
r2d2 = { version = "0.8.10" }
r2d2_sqlite = { version = "0.31.0" }

# logger
log = { version = "0.4" }
log4rs = { version = "1.4.0", features = ["pattern_encoder", "json_encoder"] }

# utilities
once_cell = { version = "1.21.3", features = ["parking_lot"] }
serde = { version = "1.0.219" }
serde_json = { version = "1.0.142" }
toml = { version = "0.8.23" }
uuid = { version = "1.17.0" }
chrono = { version = "0.4.42" }