[package]
name = "fast_command"
version = "0.1.0"
edition = "2024"

[dependencies]
# local crate
tools = { path = "../tools" }
common = { path = "../common" }
process_monitor = { path = "../process_monitor" }

# online crate
uuid = { workspace = true }
sea-orm = { workspace = true }
sqlx-sqlite = { workspace = true }